
export const FOOD_PROMPTS = [
  // 1-20: DARK & MOODY (FINE DINING)
  "Editorial food photography of [UPLOADED DISH NAME], dark moody atmosphere, chiaroscuro lighting, deep shadows, rustic slate background, 8k resolution.",
  "Professional shot of [UPLOADED DISH NAME], charcoal gray background, side-lit by a single softbox, matte textures, luxury restaurant vibe.",
  "A moody, cinematic close-up of [UPLOADED DISH NAME], dark wood table, vintage silverware, scattered peppercorns, soft rim lighting.",
  "[UPLOADED DISH NAME] on a black ceramic plate, low-key lighting, steam rising, hyper-realistic textures, macro lens.",
  "Fine dining presentation of [UPLOADED DISH NAME], dark emerald green backdrop, golden hour highlights, soft focus background.",
  "Gourmet [UPLOADED DISH NAME], midnight blue linen background, dramatic spotlight, focus on texture, high-end culinary magazine style.",
  "Dark rustic aesthetic for [UPLOADED DISH NAME], cast iron accents, low light, warm amber glow, professional food styling.",
  "[UPLOADED DISH NAME] served on a hand-carved stone platter, moody shadows, minimalist plating, sharp focus on ingredients.",
  "Elegant [UPLOADED DISH NAME], velvet textures in background, soft candlelight, rich contrast, sophisticated plating.",
  "Artisanal [UPLOADED DISH NAME], dark marble surface, dramatic side lighting, macro photography, f/2.8 aperture.",
  "Industrial chic [UPLOADED DISH NAME], concrete background, moody blue tones, sharp highlights, commercial quality.",
  "[UPLOADED DISH NAME] with a dark wine-red background, soft bokeh, silver cutlery, professional lighting, hyper-detailed.",
  "Moody forest-themed [UPLOADED DISH NAME], dark wood, moss accents, soft natural light through trees, organic feel.",
  "Luxury [UPLOADED DISH NAME], gold leaf accents, black silk background, sharp focus, high-speed photography style.",
  "Shadowy close-up of [UPLOADED DISH NAME], glistening textures, steam, dark ceramic bowl, cinematic feel.",
  "Rustic night-time [UPLOADED DISH NAME], warm lantern light, dark wood, cozy atmosphere, high resolution.",
  "[UPLOADED DISH NAME] on a weathered metal tray, moody lighting, smoke swirls, gritty texture, professional edit.",
  "Modern dark aesthetic [UPLOADED DISH NAME], matte black everything, vibrant food colors, sharp contrast, 8k.",
  "Intimate dinner setting with [UPLOADED DISH NAME], dark room, single candle light, soft focus, romantic mood.",
  "Chef's special [UPLOADED DISH NAME], dark kitchen background, stainless steel reflections, professional action shot.",

  // 21-40: BRIGHT & AIRY (CAFE & LIFESTYLE)
  "Bright and airy photography of [UPLOADED DISH NAME], high-key lighting, white marble tabletop, soft morning sunlight.",
  "Fresh [UPLOADED DISH NAME], light linen napkins, pastel tones, natural window light, clean composition.",
  "Vibrant [UPLOADED DISH NAME], Scandinavian design influence, light oak wood, bright shadows, lifestyle magazine style.",
  "Macro shot of [UPLOADED DISH NAME], white-on-white aesthetic, soft diffused glow, fresh herbs, dew drops.",
  "[UPLOADED DISH NAME] served in a bright sunlit kitchen, blurred garden background, cheerful summer vibes.",
  "Minimalist [UPLOADED DISH NAME], white ceramic plate, bright natural light, top-down flat lay, clean and crisp.",
  "Brunch style [UPLOADED DISH NAME], light blue wooden table, coffee cup in background, soft airy feel, f/4.0.",
  "Healthy lifestyle [UPLOADED DISH NAME], bright greens, white background, high-speed photography, sharp and fresh.",
  "Boho-chic [UPLOADED DISH NAME], macrame textures, bright sunlight, plants in background, warm airy tones.",
  "Modern cafe [UPLOADED DISH NAME], marble counter, blurred espresso machine, bright morning light, 4k photorealistic.",
  "Springtime [UPLOADED DISH NAME], floral accents, bright soft lighting, pastel background, delicate plating.",
  "Coastal vibe [UPLOADED DISH NAME], light sand-colored wood, bright blue accents, soft natural light, airy atmosphere.",
  "Clean eating [UPLOADED DISH NAME], minimalist glass bowl, bright white light, focus on raw textures, professional.",
  "Sunny balcony setting with [UPLOADED DISH NAME], bright shadows, city skyline blurred, high-end travel blog style.",
  "Artisan [UPLOADED DISH NAME], light gray stone, bright diffused light, fresh garnishes, crisp resolution.",
  "Morning dew [UPLOADED DISH NAME], bright garden setting, soft bokeh, vibrant colors, macro details.",
  "Modern white studio shot of [UPLOADED DISH NAME], shadowless lighting, ultra-clean, commercial product photography.",
  "Whimsical [UPLOADED DISH NAME], bright lighting, colorful background, soft focus, high-end pastry shop aesthetic.",
  "Farm-fresh [UPLOADED DISH NAME], bright white barn wood, natural light, vibrant ingredients, sharp focus.",
  "Zesty [UPLOADED DISH NAME], bright yellow accents, high-key lighting, fresh and energetic mood.",

  // 41-60: RUSTIC & ORGANIC
  "Rustic farm-to-table [UPLOADED DISH NAME], weathered wooden table, cast iron elements, burlap textures, earth tones.",
  "Authentic [UPLOADED DISH NAME], overhead flat lay, scattered raw ingredients, flour dusting, warm cozy lighting.",
  "Country-style [UPLOADED DISH NAME], afternoon sun through a farmhouse window, copper pots, rich organic textures.",
  "Hearty [UPLOADED DISH NAME], artisanal handmade bowl, dried herbs, soft autumn light, nostalgic mood.",
  "Professional outdoor photography of [UPLOADED DISH NAME], picnic setting, dappled sunlight, vineyard background.",
  "Tuscan kitchen style [UPLOADED DISH NAME], terracotta surfaces, warm golden hour light, olive branch accents.",
  "Vintage [UPLOADED DISH NAME], antique silverware, sepia tones, soft film grain, rustic wooden background.",
  "Winter comfort [UPLOADED DISH NAME], knitted blanket texture, warm fireplace glow, rustic wooden tray, steam.",
  "Harvest [UPLOADED DISH NAME], pumpkin and leaf accents, rustic orange tones, soft natural lighting.",
  "[UPLOADED DISH NAME] on a butcher block, chef's knife, raw spices, rustic workshop vibe, professional lighting.",
  "Traditional [UPLOADED DISH NAME], handmade pottery, linen textures, soft shadows, warm homey feel.",
  "Rustic bakery style [UPLOADED DISH NAME], flour on table, warm light, wooden peel, authentic textures.",
  "Mountain cabin [UPLOADED DISH NAME], heavy wood table, fur texture, firelight, cozy and rustic.",
  "Garden-to-table [UPLOADED DISH NAME], terracotta pots, bright organic light, soil and herb textures.",
  "Old world [UPLOADED DISH NAME], stone wall background, candlelight, rustic pewter plate, cinematic.",
  "[UPLOADED DISH NAME] with sourdough bread, rustic crumbs, warm side lighting, artisan feel.",
  "Cottagecore [UPLOADED DISH NAME], lace tablecloth, wildflowers, soft natural light, rustic charm.",
  "Mediterranean [UPLOADED DISH NAME], blue tiles, rustic wood, bright sun, lemon accents.",
  "Slow-cooked [UPLOADED DISH NAME], bubbling texture, rustic ceramic pot, soft warm lighting.",
  "Market style [UPLOADED DISH NAME], brown paper packaging, rustic crate, natural light, fresh and raw.",

  // 61-80: MODERN & MINIMALIST
  "Minimalist [UPLOADED DISH NAME], solid matte beige background, sharp focus, geometric plating, studio lighting.",
  "Modernist [UPLOADED DISH NAME], top-down view, centered composition, negative space, vibrant colors.",
  "Studio shot of [UPLOADED DISH NAME], floating elements, splash effects, high-speed photography, white background.",
  "[UPLOADED DISH NAME] on a glass surface, reflection visible, soft neon accents, futuristic culinary style.",
  "Symmetry-focused photography of [UPLOADED DISH NAME], industrial concrete background, sharp contrast.",
  "Zen-style [UPLOADED DISH NAME], slate plate, bamboo textures, minimalist lighting, calm atmosphere.",
  "High-tech kitchen [UPLOADED DISH NAME], stainless steel, blue LED accents, sharp professional focus.",
  "Monochromatic [UPLOADED DISH NAME], shades of gray, sharp focus on food color, ultra-modern.",
  "Avant-garde [UPLOADED DISH NAME], creative plating, abstract background, sharp studio lighting.",
  "Pop-art style [UPLOADED DISH NAME], bold colors, flat lighting, high contrast, vibrant and modern.",
  "Geometric [UPLOADED DISH NAME], square plate, linear shadows, minimalist architectural style.",
  "Clean lines [UPLOADED DISH NAME], matte surface, sharp focus, high-end tech aesthetic.",
  "Luxury hotel style [UPLOADED DISH NAME], white glove service feel, minimalist and perfect.",
  "Molecular gastronomy [UPLOADED DISH NAME], smoke bubbles, minimalist glass, professional studio.",
  "[UPLOADED DISH NAME] on a circular stone, soft gray background, minimalist lighting, 8k.",
  "Deconstructed [UPLOADED DISH NAME], artistic arrangement, minimalist white space, sharp focus.",
  "Urban chic [UPLOADED DISH NAME], loft background, brick and metal, modern soft lighting.",
  "Transparent aesthetic [UPLOADED DISH NAME], acrylic surfaces, light refraction, modern look.",
  "Bold [UPLOADED DISH NAME], solid color backdrop, hard shadows, fashion photography style.",
  "Sleek [UPLOADED DISH NAME], polished marble, metallic accents, minimalist professional shot.",

  // 81-100: MACRO & TEXTURE (FOOD PORN)
  "Extreme macro of [UPLOADED DISH NAME], focus on texture, glistening oil, steam, shallow depth of field.",
  "Hyper-detailed [UPLOADED DISH NAME], sauce dripping, crispy golden edges, soft bokeh, vibrant saturation.",
  "Slow-motion style capture of [UPLOADED DISH NAME], melting cheese, steam curls, intricate details.",
  "Close-up of [UPLOADED DISH NAME], focus on garnish, vibrant greens, salt crystals visible.",
  "Indulgent [UPLOADED DISH NAME], rich colors, soft textures, creamy elements, high-end blog quality.",
  "Sensory [UPLOADED DISH NAME], crunch texture visible, steam, warmth, macro lens, f/1.8.",
  "The 'Hero' shot of [UPLOADED DISH NAME], perfect lighting, glistening surfaces, appetizing and rich.",
  "Dripping [UPLOADED DISH NAME], liquid texture, high-speed freeze frame, professional commercial style.",
  "Golden crust [UPLOADED DISH NAME], macro focus on crispiness, warm lighting, blurred background.",
  "Velvety [UPLOADED DISH NAME], focus on smooth texture, soft lighting, indulgent mood.",
  "Sizzling [UPLOADED DISH NAME], focus on bubbles and heat, steam, dark background, macro.",
  "Vibrant spices on [UPLOADED DISH NAME], focus on grain and color, macro photography, sharp.",
  "Layered [UPLOADED DISH NAME], focus on cross-section, structural detail, professional styling.",
  "Juicy [UPLOADED DISH NAME], glistening moisture, bright highlights, mouth-watering macro.",
  "Perfectly glazed [UPLOADED DISH NAME], reflection on sauce, macro focus, studio lighting.",
  "Artisan texture of [UPLOADED DISH NAME], focus on crumb and fiber, natural light, high res.",
  "Frosty/Chilled [UPLOADED DISH NAME], condensation drops, ice crystals, macro focus, cold blue light.",
  "Charred texture of [UPLOADED DISH NAME], focus on grill marks, smoky atmosphere, macro.",
  "Effervescent [UPLOADED DISH NAME], bubbles, textures, macro focus, bright and energetic.",
  "The ultimate close-up of [UPLOADED DISH NAME], 100mm macro lens, every detail visible, masterpiece."
];
